package uk.ac.imperial.lpgdash

import java.util.List
import java.util.ArrayList

import uk.ac.imperial.lpgdash.allocators.RationAllocator
import uk.ac.imperial.lpgdash.ProvisionPool
import uk.ac.imperial.lpgdash.actions.*
import uk.ac.imperial.lpgdash.facts.*
import uk.ac.imperial.lpgdash.RoundType

global org.apache.log4j.Logger logger
global org.drools.runtime.StatefulKnowledgeSession session

rule "Ration resource allocation"
	no-loop
	when
		$r : Round( type == RoundType.DEMAND, $t : number )
		$c : Cluster( allocationMethod == Allocation.RATION )
		$pool : ProvisionPool( cluster == $c )
		$poolMembers : List(size > 0) from accumulate( MemberOf( cluster == $c, $p : player ), collectList( $p ) )
	then
		logger.info("Rationing resources for " + $c);
		RationAllocator.allocate(session, $poolMembers, $pool.getQuantity(), $t );
		modify( $pool ) {
			setQuantity(0);
		}
end
